# Generated by Django 5.0.6 on 2024-05-23 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(default=0)),
                ('code', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 14, 46, 28, 594534)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 14, 46, 28, 594533)),
        ),
        migrations.AlterField(
            model_name='indexesphysios',
            name='for_week',
            field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 23, 12, 46, 28, 596535, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 5, 23, 14, 46, 28, 596536)),
        ),
        migrations.AlterField(
            model_name='laxoutuserindexcreationlog',
            name='for_week',
            field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='laxoutuserpains',
            name='for_week',
            field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='physioindexcreationlog',
            name='for_week',
            field=models.IntegerField(default=21),
        ),
    ]
