# Generated by Django 5.0 on 2024-01-02 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 23, 46, 58, 163058)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 23, 46, 58, 163058)),
        ),
        migrations.AlterField(
            model_name='indexeslaxoutuser',
            name='creation_date',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='indexesphysios',
            name='for_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 2, 22, 46, 58, 164057, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 1, 2, 23, 46, 58, 164057)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='user_uid',
            field=models.CharField(default='586191f2-00b5-49d7-82a9-0665767908b2', max_length=420),
        ),
    ]
