# Generated by Django 5.0 on 2024-02-02 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0002_alter_doneexercises_date_alter_doneworkouts_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laxout_exercise',
            name='first',
        ),
        migrations.RemoveField(
            model_name='laxout_exercise',
            name='ignore',
        ),
        migrations.RemoveField(
            model_name='laxout_exercise',
            name='second',
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 17, 34, 39, 8060)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 17, 34, 39, 8060)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 2, 16, 34, 39, 11061, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 2, 2, 17, 34, 39, 11061)),
        ),
    ]
