# Generated by Django 5.0 on 2024-02-22 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0002_laxtree_laxoutuser_lax_tree_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laxoutuser',
            name='email_adress',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='laxoutuser',
            name='instruction_in_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 17, 55, 0, 863733)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 17, 55, 0, 862732)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 22, 16, 55, 0, 865733, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 2, 22, 17, 55, 0, 865733)),
        ),
    ]
