# Generated by Django 5.0 on 2024-02-02 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0003_remove_laxout_exercise_first_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laxout_exercise_model',
            name='ignore',
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 17, 39, 1, 909357)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 17, 39, 1, 909357)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 2, 16, 39, 1, 912356, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 2, 2, 17, 39, 1, 912357)),
        ),
    ]
