# Generated by Django 5.0 on 2024-02-24 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0003_laxoutuser_email_adress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessControll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('better', models.BooleanField(default=False)),
                ('created_by', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 24, 18, 22, 17, 538402)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 24, 18, 22, 17, 538401)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 24, 17, 22, 17, 540403, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 2, 24, 18, 22, 17, 540404)),
        ),
    ]
