# Generated by Django 5.0.6 on 2024-06-05 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0004_remove_aitrainingdata_related_exercises_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 17, 32, 25, 159251)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 17, 32, 25, 159251)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 5, 15, 32, 25, 161252, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 6, 5, 17, 32, 25, 161252)),
        ),
        migrations.CreateModel(
            name='AiTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness', models.CharField(default='', max_length=200)),
                ('created_by', models.IntegerField(default=0)),
                ('created_for', models.IntegerField(default=0)),
                ('related_exercises', models.ManyToManyField(to='laxout_app.aiexercise')),
            ],
        ),
    ]
