# Generated by Django 5.0 on 2024-01-04 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0005_alter_doneexercises_date_alter_doneworkouts_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexeslaxoutuser',
            name='nine_ten',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indexeslaxoutuser',
            name='six_eight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indexeslaxoutuser',
            name='theree_five',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indexeslaxoutuser',
            name='zero_two',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 11, 22, 12, 441635)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 11, 22, 12, 441635)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 4, 10, 22, 12, 442635, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 1, 4, 11, 22, 12, 443636)),
        ),
    ]
