# Generated by Django 5.0 on 2024-03-07 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0006_aitrainingdata_created_by_alter_doneexercises_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitrainingdata',
            name='created_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 15, 35, 27, 402051)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 15, 35, 27, 402051)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 7, 14, 35, 27, 404050, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 3, 7, 15, 35, 27, 404051)),
        ),
    ]
