# Generated by Django 5.0 on 2024-01-04 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0006_indexeslaxoutuser_nine_ten_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexeslaxoutuser',
            name='nine_ten',
        ),
        migrations.RemoveField(
            model_name='indexeslaxoutuser',
            name='six_eight',
        ),
        migrations.RemoveField(
            model_name='indexeslaxoutuser',
            name='theree_five',
        ),
        migrations.RemoveField(
            model_name='indexeslaxoutuser',
            name='zero_two',
        ),
        migrations.AddField(
            model_name='laxoutuser',
            name='nine_ten',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='laxoutuser',
            name='six_eight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='laxoutuser',
            name='theree_five',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='laxoutuser',
            name='zero_two',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 11, 26, 4, 555132)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 11, 26, 4, 555132)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 4, 10, 26, 4, 557131, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 1, 4, 11, 26, 4, 557132)),
        ),
    ]
