# Generated by Django 5.0 on 2024-02-03 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0006_laxoutexercisorderforuser_alter_doneexercises_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LaxoutExercisOrderForUser',
            new_name='Laxout_Exercise_Order_For_User',
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 9, 4, 50, 298667)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 9, 4, 50, 298667)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 3, 8, 4, 50, 301668, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 2, 3, 9, 4, 50, 301668)),
        ),
    ]
