# Generated by Django 5.0 on 2024-01-04 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0007_remove_indexeslaxoutuser_nine_ten_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaxoutUserPains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_month', models.IntegerField(default=1)),
                ('created_by', models.IntegerField(blank=True, default=None)),
                ('zero_two', models.IntegerField(default=0)),
                ('theree_five', models.IntegerField(default=0)),
                ('six_eight', models.IntegerField(default=0)),
                ('nine_ten', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='laxoutuser',
            name='nine_ten',
        ),
        migrations.RemoveField(
            model_name='laxoutuser',
            name='six_eight',
        ),
        migrations.RemoveField(
            model_name='laxoutuser',
            name='theree_five',
        ),
        migrations.RemoveField(
            model_name='laxoutuser',
            name='zero_two',
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 11, 41, 32, 454428)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 11, 41, 32, 454428)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 4, 10, 41, 32, 456429, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 1, 4, 11, 41, 32, 456429)),
        ),
    ]
