# Generated by Django 5.0 on 2024-02-03 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0007_rename_laxoutexercisorderforuser_laxout_exercise_order_for_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laxoutuser',
            name='first_login',
            field=models.DateField(default=datetime.datetime(2024, 2, 3, 15, 25, 43, 705945)),
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 15, 25, 43, 702944)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 15, 25, 43, 702944)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 3, 14, 25, 43, 705945, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 2, 3, 15, 25, 43, 705945)),
        ),
    ]
