# Generated by Django 5.0 on 2024-03-07 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0007_aitrainingdata_created_for_alter_doneexercises_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 19, 18, 32, 376318)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 19, 18, 32, 375317)),
        ),
        migrations.AlterField(
            model_name='laxout_exercise',
            name='execution',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 7, 18, 18, 32, 378318, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 3, 7, 19, 18, 32, 378319)),
        ),
        migrations.AlterField(
            model_name='uebungen_models',
            name='execution',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
