# Generated by Django 5.0 on 2024-02-03 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0009_alter_doneexercises_date_alter_doneworkouts_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaxoutUserIndexCreationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_month', models.IntegerField(default=2)),
                ('for_year', models.IntegerField(default=2024)),
                ('created_by', models.IntegerField(blank=True, default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='laxoutuser',
            name='first_login',
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 17, 17, 35, 243247)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 17, 17, 35, 242247)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 3, 16, 17, 35, 245247, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 2, 3, 17, 17, 35, 246248)),
        ),
    ]
