# Generated by Django 5.0 on 2024-02-03 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0010_laxoutuserindexcreationlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laxoutuserpains',
            name='for_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 17, 33, 22, 215265)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 17, 33, 22, 215265)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 3, 16, 33, 22, 219266, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 2, 3, 17, 33, 22, 219266)),
        ),
    ]
