# Generated by Django 5.0 on 2024-03-26 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0011_chatdatamodel_admin_id_alter_doneexercises_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laxoutuser',
            name='admin_has_seen_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='laxoutuser',
            name='user_has_seen_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 26, 20, 36, 35, 609990)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 26, 20, 36, 35, 608989)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 26, 19, 36, 35, 611990, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 3, 26, 20, 36, 35, 611990)),
        ),
    ]
