# Generated by Django 5.0 on 2024-04-06 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0012_laxoutuser_admin_has_seen_chat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 12, 57, 13, 970796)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 12, 57, 13, 969796)),
        ),
        migrations.AlterField(
            model_name='indexeslaxoutuser',
            name='creation_date',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='indexesphysios',
            name='for_month',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='indexesphysios',
            name='for_week',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 6, 10, 57, 13, 972796, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 4, 6, 12, 57, 13, 972797)),
        ),
        migrations.AlterField(
            model_name='laxoutuserindexcreationlog',
            name='for_month',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='laxoutuserindexcreationlog',
            name='for_week',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='laxoutuserpains',
            name='for_month',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='laxoutuserpains',
            name='for_week',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='physioindexcreationlog',
            name='for_month',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='physioindexcreationlog',
            name='for_week',
            field=models.IntegerField(default=14),
        ),
    ]
