# Generated by Django 5.0 on 2024-02-03 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0012_indexesphysios_for_week_laxoutuserpains_for_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laxoutuserindexcreationlog',
            name='for_week',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='physioindexcreationlog',
            name='for_week',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 17, 41, 37, 432046)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 17, 41, 37, 432046)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 3, 16, 41, 37, 435046, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 2, 3, 17, 41, 37, 435047)),
        ),
    ]
