# Generated by Django 5.0 on 2024-04-06 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0013_billingcount_alter_doneexercises_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcount',
            name='billing_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 12, 59, 2, 505010)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 12, 59, 2, 505010)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 6, 10, 59, 2, 507009, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 4, 6, 12, 59, 2, 508010)),
        ),
    ]
